# Generated by Django 4.1.3 on 2023-01-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birdbuy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birds',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='birds',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
