# Generated by Django 4.1.3 on 2023-01-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birdbuy', '0002_birds_image_birds_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_phone', models.IntegerField()),
                ('card_sum_enable', models.BooleanField()),
                ('cart_sum', models.IntegerField(null=True)),
            ],
        ),
    ]
