# Generated by Django 4.1.3 on 2023-01-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birdbuy', '0003_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='number_phone',
            field=models.CharField(max_length=16),
        ),
    ]
