# Generated by Django 4.1.3 on 2023-01-24 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Birdbuy', '0004_alter_content_number_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='card_sum_enable',
            new_name='cart_sum_enable',
        ),
    ]
